vich_uploader:
    db_driver: orm

    mappings:
        logo:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /logo
            # Chemin vers le dossier de stockage
            upload_destination: '%upload_directory%'
